data: 'testdata/'
logF: 'log_path'
epoch: 20
batch_size: 2
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 1
learning_rate_decay: 1.0
start_decay_at: 10
emb_size: 512
hidden_size: 512
dec_num_layers: 3
enc_num_layers: 3
bidirectional: True
dropout: 0.4
max_time_step: 100
eval_interval: 25550
save_interval: 25550
metrics: ['bleu']
shared_vocab: False
beam_size: 5
unk: False
schedule: True
hops: 1
schesamp: False
res_layers: 1
resRNN: False
selfatt: False
attemb: False
swish: False
